"""Fetches the current S&P 500 list from Wikipedia and writes src/sp500_tickers.py.

Run once now, then re-run every 2-3 months to keep the universe current.
The GENERATED file hardcodes the list, so the bot never hits the network at runtime.
"""

import io
from pathlib import Path

import pandas as pd
import requests

URL = "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies"
OUT = Path("src/sp500_tickers.py")


def main():
    resp = requests.get(URL, headers={"User-Agent": "Mozilla/5.0"}, timeout=30)
    resp.raise_for_status()

    tables = pd.read_html(io.StringIO(resp.text))
    df = tables[0]

    # IBKR wants class shares with a space ("BRK B"), Wikipedia uses a dot ("BRK.B").
    symbols = [str(s).strip().replace(".", " ") for s in df["Symbol"].tolist()]
    symbols = sorted(set(symbols))

    lines = [
        "# Auto-generated by build_tickers.py from Wikipedia's S&P 500 list.",
        "# IBKR format: class shares use a space, e.g. 'BRK B', not 'BRK.B'.",
        "# Re-run build_tickers.py every 2-3 months to refresh.",
        "",
        "SP500_TICKERS = [",
    ]
    lines += [f'    "{s}",' for s in symbols]
    lines.append("]")

    OUT.parent.mkdir(exist_ok=True)
    OUT.write_text("\n".join(lines) + "\n")

    print(f"Wrote {len(symbols)} tickers to {OUT}")
    print("First 5:", symbols[:5])
    print("Last 5:", symbols[-5:])


if __name__ == "__main__":
    main()