"""Morning prefilter: scan the S&P 500 for gappers and write watchlist.txt.

Pulls 2 daily bars per ticker from Yahoo (free, no request cap), computes the
gap from the prior close, keeps names gapping >= min-gap and priced >= min-price,
and writes the top 20 by gap to watchlist.txt.

Yahoo is used for screening only; IBKR still handles execution.
"""

import argparse
import json
import sys
import time
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import yfinance as yf

from src.sp500_tickers import SP500_TICKERS

WATCHLIST_PATH = Path("watchlist.txt")
DEFAULT_MIN_GAP_PCT = 3.0
DEFAULT_MIN_PRICE = 3.0
MAX_SURVIVORS = 20
ET = ZoneInfo("America/New_York")


def to_yahoo(ibkr_symbol):
    # IBKR "BRK B" -> Yahoo "BRK-B"
    return ibkr_symbol.replace(" ", "-")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--min-gap", type=float, default=DEFAULT_MIN_GAP_PCT)
    parser.add_argument("--min-price", type=float, default=DEFAULT_MIN_PRICE)
    parser.add_argument("--dry-run", action="store_true")
    args = parser.parse_args()

    start = time.time()
    yahoo_tickers = [to_yahoo(t) for t in SP500_TICKERS]

    data = yf.download(
        tickers=" ".join(yahoo_tickers),
        period="2d",
        interval="1d",
        group_by="ticker",
        threads=5,
        progress=False,
        auto_adjust=True,
    )

    if data is None or data.empty:
        print(json.dumps({"success": False, "error": "empty dataframe from yfinance"}))
        sys.exit(1)

    survivors = []
    below_gap = 0
    below_price = 0
    failed = []

    for tkr in yahoo_tickers:
        try:
            bars = data[tkr]
            yesterday_close = float(bars.iloc[-2]["Close"])
            today_open = float(bars.iloc[-1]["Open"])
            today_close = float(bars.iloc[-1]["Close"])
            today_high = float(bars.iloc[-1]["High"])
            today_low = float(bars.iloc[-1]["Low"])

            if yesterday_close != yesterday_close or today_close != today_close:  # NaN
                failed.append(tkr)
                continue

            gap_pct = (today_close - yesterday_close) / yesterday_close * 100

            if today_close < args.min_price:
                below_price += 1
                continue
            if gap_pct < args.min_gap:
                below_gap += 1
                continue

            survivors.append({
                "ticker": tkr,
                "gap_pct": gap_pct,
                "open": today_open,
                "prev_close": yesterday_close,
            })
        except (KeyError, IndexError, ValueError):
            failed.append(tkr)
            continue

    survivors.sort(key=lambda s: s["gap_pct"], reverse=True)
    survivors = survivors[:MAX_SURVIVORS]

    total = len(yahoo_tickers)
    fail_ratio = len(failed) / total if total else 0
    if fail_ratio >= 0.95:
        print("ALERT: Yahoo-wide failure suspected; check yfinance changelog", file=sys.stderr)
    elif fail_ratio >= 0.30:
        print(f"ALERT: yfinance degradation (failed {len(failed)}/{total})", file=sys.stderr)

    if not args.dry_run:
        now = datetime.now(ET)
        header = [
            f"# Auto-generated by morning_prefilter.py at {now:%Y-%m-%d %H:%M %Z}",
            f"# Filters: gap >= {args.min_gap}%, price >= ${args.min_price}",
            "# Source: yfinance (screening only); IBKR handles execution",
            f"# Survivors: {len(survivors)} (capped at {MAX_SURVIVORS}) of {total}",
            "#",
            "# ticker  # gap +X.XX%  open $X.XX  prev $X.XX",
        ]
        body = []
        for s in survivors:
            ibkr_sym = s["ticker"].replace("-", " ")  # back to IBKR format
            body.append(
                f'{ibkr_sym}  # gap {s["gap_pct"]:+.2f}%  open ${s["open"]:.2f}  prev ${s["prev_close"]:.2f}'
            )
        WATCHLIST_PATH.write_text("\n".join(header + body) + "\n")

    elapsed = round(time.time() - start, 2)
    summary = {
        "success": True,
        "total_screened": total,
        "survivors_count": len(survivors),
        "below_gap": below_gap,
        "below_price": below_price,
        "failed": len(failed),
        "elapsed_seconds": elapsed,
        "top_20_survivors": [f'{s["ticker"]} ({s["gap_pct"]:+.2f}%)' for s in survivors],
        "watchlist_path": str(WATCHLIST_PATH) if not args.dry_run else None,
    }
    print(json.dumps(summary, indent=2))


if __name__ == "__main__":
    main()